name: inspired_blog
description: A new Flutter project.
publish_to: 'none'

version: 1.0.2+1

environment:
     sdk: '>=2.19.2 <3.0.0'

dependencies:
     flutter:
          sdk: flutter
     cupertino_icons: ^1.0.2
     shared_preferences: ^2.2.2
     get: ^4.6.5
     intl: ^0.18.1
     fluttertoast: ^8.2.4
     loading_animation_widget: ^1.2.0+4
     http: ^0.13.6
     google_fonts: ^4.0.4
     carousel_slider: ^4.2.1
     cached_network_image: ^3.2.3
     smooth_page_indicator: ^1.1.0
     animations: ^2.0.8
     dio: ^5.4.0
     flutter_widget_from_html: ^0.14.10+1
     url_launcher: ^6.1.11
     share_plus: ^7.2.1
     youtube_player_flutter: ^8.1.2
     flutter_cache_manager: ^3.3.1

dev_dependencies:
     flutter_test:
          sdk: flutter
     flutter_lints: ^2.0.0
     flutter_launcher_icons: ^0.12.0
     flutter_native_splash: ^2.2.19

flutter_icons:
     android: true
     ios: true
     image_path: 'assets/app_icon.png'

flutter_native_splash:
     image: assets/app_icon.png
     color: '#FF9B08'

flutter:
     uses-material-design: true
     assets:
          - assets/
